amplitude_event:
  outputs:
    dev:
      dbname: dev
      host: 
      password: 
      port: 
      schema: dbt_amplitude
      threads: 1
      type: redshift
      user: 
  outputs:
    test:
      dbname: dev
      host: 
      password: 
      port: 
      schema: dbt_amplitude_test
      threads: 1
      type: redshift
      user:
  target: test
postgres_template:
  outputs:
    dev:
      dbname: template
      host: localhost
      pass: 
      port: 
      schema: public
      threads: 1
      type: postgres
      user: 
    prod:
      dbname:
      - dbname
      host:
      - host
      pass:
      - prod_password
      port:
      - port
      schema:
      - prod_schema
      threads:
      - 1 or more
      type: postgres
      user:
      - prod_username
  target: dev
